API_HOST_URL: 'https://uat.vigyanshaala.com'
APPLICATION_ID: 'org.app.vigyanshaala'
ENVIRONMENT_DISPLAY_NAME: 'VigyanShaala'
URI_SCHEME: 'uat.vigyanshaala.com'
FEEDBACK_EMAIL_ADDRESS: 'sales@titaned.com'
FAQ_URL: ''
OAUTH_CLIENT_ID: 'cFd8Le3wxWJU7uRppAx1UggW99BQXzVIibQuB5Wq'

# Keep empty to hide setting
AGREEMENT_URLS:
  PRIVACY_POLICY_URL: 'https://uat.vigyanshaala.com/privacy-policy'
  COOKIE_POLICY_URL: 'https://uat.vigyanshaala.com/cookie-policy'
  DATA_SELL_CONSENT_URL: 'https://uat.vigyanshaala.com/complaints-policy'
  TOS_URL: 'https://uat.vigyanshaala.com/terms-and-conditions'
  EULA_URL: ''
  SUPPORTED_LANGUAGES: [ ] #en is default language

DISCOVERY:
  TYPE: 'native'
  WEBVIEW:
    BASE_URL: ''
    COURSE_DETAIL_TEMPLATE: ''
    PROGRAM_DETAIL_TEMPLATE: ''

PROGRAM:
  TYPE: 'native'
  WEBVIEW:
    BASE_URL: ''
    PROGRAM_DETAIL_TEMPLATE: ''

DASHBOARD:
  TYPE: 'gallery'

FIREBASE:
  ENABLED: false
  CLOUD_MESSAGING_ENABLED: false
  PROJECT_NUMBER: ''
  PROJECT_ID: ''
  APPLICATION_ID: '' #App ID field from the Firebase console or mobilesdk_app_id from the google-services.json file.
  API_KEY: ''

BRAZE:
  ENABLED: false
  PUSH_NOTIFICATIONS_ENABLED: false

GOOGLE:
  ENABLED: false
  CLIENT_ID: ''

MICROSOFT:
  ENABLED: false
  CLIENT_ID: ''
  PACKAGE_SIGNATURE: ''

FACEBOOK:
  ENABLED: false
  FACEBOOK_APP_ID: ''
  CLIENT_TOKEN: ''

BRANCH:
  ENABLED: false
  KEY: ''
  URI_SCHEME: ''
  HOST: ''
  ALTERNATE_HOST: ''

#Platform names
PLATFORM_NAME: "VigyanShaala"
PLATFORM_FULL_NAME: "VigyanShaala"
#App sourceSets dir
THEME_DIRECTORY: "VigyanShaala"
#tokenType enum accepts JWT and BEARER only
TOKEN_TYPE: "JWT"
#feature flag for activating What’s New feature
WHATS_NEW_ENABLED: false
PRE_LOGIN_EXPERIENCE_ENABLED: true
#feature flag enable Social Login buttons
SOCIAL_AUTH_ENABLED: false
#feature flag to enable registration from app
REGISTRATION_ENABLED: true
#feature flag to do the authentication flow in the browser to log in
BROWSER_LOGIN: false
#feature flag to do the registration for in the browser
BROWSER_REGISTRATION: false
#Course navigation feature flags
UI_COMPONENTS:
  COURSE_DROPDOWN_NAVIGATION_ENABLED: true
  COURSE_UNIT_PROGRESS_ENABLED: true
  COURSE_DOWNLOAD_QUEUE_SCREEN: true
